const fs = require('fs/promises');
const path = require('path');
const { buildLetterData, formatDate } = require('./letterFormatter');

const PDF_DIR = path.join(__dirname, '..', 'generated-pdfs');
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const LEFT = 62;
const RIGHT = 62;
const TOP = 62;
const BOTTOM = 62;
const LINE_HEIGHT = 16;

function escapePdfText(value) {
  return String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');
}

function wrapText(text, maxChars = 86) {
  const words = String(text || '').split(/\s+/).filter(Boolean);
  const lines = [];
  let current = '';

  words.forEach((word) => {
    const next = current ? `${current} ${word}` : word;
    if (next.length > maxChars && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  });

  if (current) lines.push(current);
  return lines.length ? lines : [''];
}

function addWrapped(lines, text, options = {}) {
  const wrapped = wrapText(text, options.maxChars);
  wrapped.forEach((line) => lines.push({ text: line, font: options.font || 'regular', size: options.size || 11 }));
}

function letterLines(input) {
  const data = buildLetterData(input);
  const lines = [];
  lines.push({ text: 'MESOB INTERNAL MESSAGING SYSTEM', font: 'bold', size: 16, center: true });
  lines.push({ text: `${data.templateType.replace(/_/g, ' ').toUpperCase()} INTERNAL CORRESPONDENCE`, font: 'regular', size: 10, center: true });
  lines.push({ spacer: 14 });
  lines.push({ text: `Reference No: ${data.referenceNumber}`, font: 'bold', size: 11 });
  lines.push({ text: `Date: ${formatDate(data.date)}`, font: 'regular', size: 11 });
  lines.push({ spacer: 8 });
  lines.push({ text: `From: ${data.senderName}`, font: 'regular', size: 11 });
  lines.push({ text: `To: ${data.recipientName}`, font: 'regular', size: 11 });
  lines.push({ text: `Subject: ${data.subject}`, font: 'bold', size: 12 });
  lines.push({ spacer: 10 });

  if (data.templateType === 'memo') {
    lines.push({ text: 'MEMO', font: 'bold', size: 14, center: true });
  } else if (data.templateType === 'notice') {
    lines.push({ text: 'NOTICE', font: 'bold', size: 14, center: true });
  } else if (data.templateType === 'circular') {
    lines.push({ text: 'CIRCULAR', font: 'bold', size: 14, center: true });
    lines.push({ text: 'Dear Team,', font: 'regular', size: 11 });
  } else if (data.templateType === 'request_form') {
    lines.push({ text: `Requested by: ${data.senderName}`, font: 'regular', size: 11 });
    lines.push({ text: `Submitted to: ${data.recipientName}`, font: 'regular', size: 11 });
    lines.push({ spacer: 8 });
  } else {
    lines.push({ text: `Dear ${data.recipientName},`, font: 'regular', size: 11 });
  }

  String(data.body || '').split(/\n{2,}/).forEach((paragraph) => {
    lines.push({ spacer: 6 });
    addWrapped(lines, paragraph.replace(/\n/g, ' '), { size: 11 });
  });

  lines.push({ spacer: 12 });
  if (data.templateType === 'memo') {
    lines.push({ text: 'For your information and necessary action.', font: 'regular', size: 11 });
  } else {
    lines.push({ text: 'Kind regards,', font: 'regular', size: 11 });
  }

  if (data.attachments.length) {
    lines.push({ spacer: 12 });
    lines.push({ text: 'Attachments:', font: 'bold', size: 11 });
    data.attachments.forEach((item) => {
      const size = Number(item.size);
      const sizeLabel = Number.isFinite(size) && size > 0 ? ` (${Math.ceil(size / 1024)} KB)` : '';
      addWrapped(lines, `- ${item.name}${sizeLabel}`, { size: 10, maxChars: 92 });
    });
  }

  // Watermark (drawn near bottom center on each page via PDF stream)
  // Keeping it lightweight: add text lines at the end so it shows without requiring PDF image support.
  lines.push({ spacer: 18 });
  lines.push({ text: 'MESOB', font: 'regular', size: 9, center: true, watermark: true });
  lines.push({ spacer: 8 });
  lines.push({ text: data.senderName, font: 'bold', size: 11 });
  if (data.senderTitle) lines.push({ text: data.senderTitle, font: 'regular', size: 10 });
  lines.push({ spacer: 16 });
  lines.push({ text: 'Generated by MESOB Internal Messaging System', font: 'regular', size: 8, center: true });
  return lines;
}

function paginate(lines) {
  const pages = [[]];
  let y = TOP;

  lines.forEach((line) => {
    const height = line.spacer || LINE_HEIGHT;
    if (y + height > PAGE_HEIGHT - BOTTOM) {
      pages.push([]);
      y = TOP;
    }
    pages[pages.length - 1].push(line);
    y += height;
  });

  return pages;
}

function streamForPage(lines) {
  let y = PAGE_HEIGHT - TOP;
  const commands = [
    '0.95 0.95 0.95 rg',
    `0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT} re f`,
    '1 1 1 rg',
    `44 40 ${PAGE_WIDTH - 88} ${PAGE_HEIGHT - 80} re f`,
    '0.19 0.31 0.63 RG',
    '2 w',
    `44 ${PAGE_HEIGHT - 46} m ${PAGE_WIDTH - 44} ${PAGE_HEIGHT - 46} l S`,
    '0 0 0 rg'
  ];

  lines.forEach((line) => {
    if (line.spacer) {
      y -= line.spacer;
      return;
    }
    const font = line.font === 'bold' ? 'F2' : 'F1';
    const size = line.size || 11;
    const approxWidth = String(line.text || '').length * size * 0.48;
    const x = line.center ? Math.max(LEFT, (PAGE_WIDTH - approxWidth) / 2) : LEFT;

    // Optional watermark styling (light gray)
    if (line.watermark) {
      commands.push('0.75 0.75 0.75 rg');
    }

    commands.push(`BT /${font} ${size} Tf ${x.toFixed(2)} ${y.toFixed(2)} Td (${escapePdfText(line.text)}) Tj ET`);

    if (line.watermark) {
      commands.push('0 0 0 rg');
    }

    y -= Math.max(LINE_HEIGHT, size + 5);
  });

  return commands.join('\n');
}

function buildPdf(pages) {
  const objects = [];
  const addObject = (content) => {
    objects.push(content);
    return objects.length;
  };

  const catalogId = addObject('');
  const pagesId = addObject('');
  const fontRegularId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  const fontBoldId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  const pageIds = [];

  pages.forEach((pageLines) => {
    const stream = streamForPage(pageLines);
    const contentId = addObject(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}\nendstream`);
    const pageId = addObject(`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontRegularId} 0 R /F2 ${fontBoldId} 0 R >> >> /Contents ${contentId} 0 R >>`);
    pageIds.push(pageId);
  });

  objects[catalogId - 1] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;
  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageIds.length} >>`;

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, 'utf8');
}

async function generateLetterPdf(input) {
  await fs.mkdir(PDF_DIR, { recursive: true });
  const reference = String(input.referenceNumber || `message-${Date.now()}`).replace(/[^a-z0-9-]/gi, '_');
  const fileName = `${reference}.pdf`;
  const filePath = path.join(PDF_DIR, fileName);
  const pages = paginate(letterLines(input));
  await fs.writeFile(filePath, buildPdf(pages));
  return filePath;
}

module.exports = {
  generateLetterPdf
};
